In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.3'

## creat and read

### 1D array

In [4]:
arr1=np.array([1,2,3,4,5,6,7,8,9,0])

In [5]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(10,)

In [8]:
arr1.dtype

dtype('int64')

In [9]:
arr1.ndim

1

In [10]:
arr1.size

10

### 2D array

In [12]:
arr2=np.array([[1,2,3],[4,5,6]])

In [13]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 3)

In [17]:
arr2.size

6

### 3D array

In [22]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[1,2,3],[4,5,6]]])

In [23]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [24]:
arr3.shape

(3, 2, 3)

# Creat random array 

In [25]:
randomarr= np.random.rand(3,2,3)

In [26]:
randomarr

array([[[0.99203771, 0.26048028, 0.92880024],
        [0.85608249, 0.14580884, 0.27598826]],

       [[0.38325521, 0.90753733, 0.27483173],
        [0.6481452 , 0.94968431, 0.86530741]],

       [[0.45532877, 0.29538688, 0.87589463],
        [0.8731768 , 0.65550955, 0.99905403]]])

In [27]:
randomarr.dtype

dtype('float64')

In [30]:
zeros=np.zeros((3,2,3))

In [31]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [35]:
arr3[0][0][1]

np.int64(2)

In [36]:
arr3[0:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
arr3[1][0][1]

np.int64(8)

In [38]:
arr3[1,0,1]

np.int64(8)

In [39]:
a1=np.random.rand(2,3,2)
a2=np.random.rand(2,3,2)


In [42]:
a1
a2

array([[[0.50237047, 0.12106121],
        [0.53996783, 0.76131183],
        [0.95435213, 0.22867729]],

       [[0.93218955, 0.36849457],
        [0.26698094, 0.98504708],
        [0.83533914, 0.42015335]]])

In [41]:
a2

array([[[0.50237047, 0.12106121],
        [0.53996783, 0.76131183],
        [0.95435213, 0.22867729]],

       [[0.93218955, 0.36849457],
        [0.26698094, 0.98504708],
        [0.83533914, 0.42015335]]])

In [43]:
a1

array([[[0.73671876, 0.66469491],
        [0.59867367, 0.44334507],
        [0.60193923, 0.83963584]],

       [[0.29157382, 0.12612927],
        [0.84914756, 0.44245941],
        [0.72949235, 0.68343803]]])

# basic Math Operation

In [45]:
np.add(a1,a2)

array([[[1.23908923, 0.78575612],
        [1.1386415 , 1.20465689],
        [1.55629136, 1.06831314]],

       [[1.22376337, 0.49462384],
        [1.11612849, 1.42750649],
        [1.56483149, 1.10359138]]])

In [46]:
np.subtract(a1,a2)

array([[[ 0.2343483 ,  0.5436337 ],
        [ 0.05870584, -0.31796676],
        [-0.3524129 ,  0.61095855]],

       [[-0.64061573, -0.2423653 ],
        [ 0.58216662, -0.54258767],
        [-0.10584679,  0.26328467]]])

In [47]:
np.divide(a1,a2)

array([[[1.46648502, 5.4905687 ],
        [1.108721  , 0.5823436 ],
        [0.63073075, 3.67170621]],

       [[0.31278383, 0.34228257],
        [3.18055503, 0.4491759 ],
        [0.87328884, 1.62663947]]])

In [48]:
np.multiply(a1,a2)

array([[[0.37010575, 0.08046877],
        [0.32326452, 0.33752384],
        [0.57446198, 0.19200565]],

       [[0.27180207, 0.04647795],
        [0.22670621, 0.43584335],
        [0.60937351, 0.28714878]]])

### Staticstical opretions

In [49]:
sqrt = np.sqrt(25)
abss= np.abs(-2)
power= np.power(2,8)
log= np.log(25)
mins= np.min(a1)
maxs= np.max(a2)


In [50]:
sqrt

np.float64(5.0)

In [51]:
abss

np.int64(2)

In [52]:
power

np.int64(256)

In [53]:
log

np.float64(3.2188758248682006)

In [54]:
mins

np.float64(0.12612927020353426)

In [55]:
maxs

np.float64(0.9850470795874584)

## Update

In [57]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [58]:
arr3[0,0,2]=20

In [59]:
arr3

array([[[ 1,  2, 20],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [60]:
arr3[0,0,2]=3

In [61]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [62]:
arr3.sort()
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

# Reshape

In [63]:
arr3.shape

(3, 2, 3)

In [64]:
arr3_reshape= arr3.reshape((2,3,3))

In [65]:
arr3_reshape

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [ 1,  2,  3],
        [ 4,  5,  6]]])

In [68]:
arr3_reshape= arr3.reshape((2,3,-1))

In [69]:
arr3_reshape

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [ 1,  2,  3],
        [ 4,  5,  6]]])

## Appending and inserting

In [70]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Creating new arrey

In [72]:
new_arrey =np.ones((3,2,3))

In [73]:
new_arrey

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [74]:
appd =np.append(zeros,new_arrey,axis=0)

In [75]:
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Inserting

In [78]:
inser=np.insert(zeros,2,new_arrey,axis=0)

In [79]:
inser

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

# Deleting

In [80]:
arr4=np.random.rand(3,2,3)

In [81]:
arr4

array([[[0.97751687, 0.89050143, 0.32923725],
        [0.12573391, 0.10800204, 0.69923416]],

       [[0.11765409, 0.08273359, 0.01407226],
        [0.51134462, 0.02119953, 0.34919876]],

       [[0.70467685, 0.624333  , 0.81353186],
        [0.72981552, 0.61849381, 0.546261  ]]])

In [83]:
 arr5=np.delete(arr4,0,axis=1)

In [84]:
np.save('new_array',arr5)

In [85]:
np.load('new_array.npy')

array([[[0.12573391, 0.10800204, 0.69923416]],

       [[0.51134462, 0.02119953, 0.34919876]],

       [[0.72981552, 0.61849381, 0.546261  ]]])